### ISSUE TITLE
项目使用tomcat部署后不能显示本地转换好的本地图片

### ISSUE THREAD

**Issue by gaohanghang** [QixinLi/Img2Ascii#1]
$("#ASCII").attr("src","/asciiimg/"+code+"."+lastindex);

这个显示不了本地转换好的图片，请问怎么做的

[![Pagma6.md.jpg](https://s1.ax1x.com/2018/07/29/Pagma6.md.jpg)](https://imgchr.com/i/Pagma6)

[![PagMGD.md.jpg](https://s1.ax1x.com/2018/07/29/PagMGD.md.jpg)](https://imgchr.com/i/PagMGD)

**Comment by gaohanghang** [comment]
代码

https://github.com/gaohanghang/Img2Ascii

**Comment by gaohanghang** [comment]
C盘目录结构

![snipaste_2018-07-29_19-48-42](https://user-images.githubusercontent.com/20310190/43365999-6b99718a-9368-11e8-98d5-2bd4ab8d7804.jpg)

**Comment by gaohanghang** [comment]
最终解决方案

https://blog.csdn.net/Cheney550995353/article/details/70185282

**Comment by QixinLi** [comment]
是的。服务器环境下需要配置tomcat的地址映射以达到绝对路径和相对路径的转换。
（抱歉 最近没怎么上git 回复晚了）
